/* tslint:disable */
/* eslint-disable */
/**
 * Mój Projekt w Nest
 * Przykładowy projekt w Node.js i TypeScript
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AuthRegisterDto
 */
export interface AuthRegisterDto {
    /**
     * 
     * @type {string}
     * @memberof AuthRegisterDto
     */
    name: any;
    /**
     * 
     * @type {string}
     * @memberof AuthRegisterDto
     */
    email: any;
    /**
     * 
     * @type {string}
     * @memberof AuthRegisterDto
     */
    password: any;
}
