/* tslint:disable */
/* eslint-disable */
/**
 * Mój Projekt w Nest
 * Przykładowy projekt w Node.js i TypeScript
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface RemoveUserResponse
 */
export interface RemoveUserResponse {
    /**
     * 
     * @type {any}
     * @memberof RemoveUserResponse
     */
    status: any;
    /**
     * 
     * @type {number}
     * @memberof RemoveUserResponse
     */
    removedId: any;
}
