/* tslint:disable */
/* eslint-disable */
/**
 * Mój Projekt w Nest
 * Przykładowy projekt w Node.js i TypeScript
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CreateUserDto
 */
export interface CreateUserDto {
    /**
     * Name of the user
     * @type {string}
     * @memberof CreateUserDto
     */
    name: any;
    /**
     * your email address
     * @type {string}
     * @memberof CreateUserDto
     */
    email: any;
    /**
     * password min 3 chars
     * @type {string}
     * @memberof CreateUserDto
     */
    password: any;
    /**
     * 
     * @type {number}
     * @memberof CreateUserDto
     */
    partner: any;
}
