/* tslint:disable */
/* eslint-disable */
/**
 * Nest API Example
 * Przykładowy projekt w Node.js i TypeScript
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface FindQuotesResponseDto
 */
export interface FindQuotesResponseDto {
    /**
     * 
     * @type {number}
     * @memberof FindQuotesResponseDto
     */
    pageIndex: any;
    /**
     * 
     * @type {number}
     * @memberof FindQuotesResponseDto
     */
    pageSize: any;
    /**
     * 
     * @type {number}
     * @memberof FindQuotesResponseDto
     */
    total: any;
    /**
     * 
     * @type {Array&lt;QuoteEntity&gt;}
     * @memberof FindQuotesResponseDto
     */
    data: any;
}
