/* tslint:disable */
/* eslint-disable */
/**
 * Nest API Example
 * Przykładowy projekt w Node.js i TypeScript
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PhotoEntity
 */
export interface PhotoEntity {
    /**
     * 
     * @type {number}
     * @memberof PhotoEntity
     */
    id: any;
    /**
     * 
     * @type {string}
     * @memberof PhotoEntity
     */
    filename: any;
    /**
     * 
     * @type {string}
     * @memberof PhotoEntity
     */
    description: any;
    /**
     * 
     * @type {number}
     * @memberof PhotoEntity
     */
    size: any;
    /**
     * 
     * @type {UserEntity}
     * @memberof PhotoEntity
     */
    user: any;
}
