/* tslint:disable */
/* eslint-disable */
/**
 * Nest API Example
 * Przykładowy projekt w Node.js i TypeScript
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface QuoteEntity
 */
export interface QuoteEntity {
    /**
     * Fajny cytat
     * @type {string}
     * @memberof QuoteEntity
     */
    text: any;
    /**
     * Kto powiedział
     * @type {string}
     * @memberof QuoteEntity
     */
    author: any;
    /**
     * 
     * @type {number}
     * @memberof QuoteEntity
     */
    id: any;
}
