/* tslint:disable */
/* eslint-disable */
/**
 * Nest API Example
 * Przykładowy projekt w Node.js i TypeScript
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UploadResponseDto
 */
export interface UploadResponseDto {
    /**
     * 
     * @type {PhotoEntity}
     * @memberof UploadResponseDto
     */
    photo: any;
    /**
     * 
     * @type {any}
     * @memberof UploadResponseDto
     */
    thumb: any;
    /**
     * 
     * @type {any}
     * @memberof UploadResponseDto
     */
    file: any;
    /**
     * 
     * @type {any}
     * @memberof UploadResponseDto
     */
    body: any;
}
