/* tslint:disable */
/* eslint-disable */
/**
 * Nest API Example
 * Przykładowy projekt w Node.js i TypeScript
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UserRegisterResponseDto
 */
export interface UserRegisterResponseDto {
    /**
     * 
     * @type {UserEntity}
     * @memberof UserRegisterResponseDto
     */
    user: any;
}
