/* tslint:disable */
/* eslint-disable */
/**
 * Nest API Example
 * Przykładowy projekt w Node.js i TypeScript
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UserEntity
 */
export interface UserEntity {
    /**
     * 
     * @type {number}
     * @memberof UserEntity
     */
    id: any;
    /**
     * 
     * @type {string}
     * @memberof UserEntity
     */
    name: any;
    /**
     * 
     * @type {string}
     * @memberof UserEntity
     */
    email: any;
    /**
     * 
     * @type {string}
     * @memberof UserEntity
     */
    password: any;
    /**
     * 
     * @type {Array&lt;UserRoleEntity&gt;}
     * @memberof UserEntity
     */
    roles?: any;
}
